### ISSUE TITLE
Sensor stops working after some time

### ISSUE THREAD

**Issue by ElectricCookie** [TillFleisch/ESPHome-HLK-LD2450#1]
Hi, awesome work and very nice to see fully polygon based zone support! 

I'm having trouble with the sensor stopping to work after some time. 

I first thought it might be a problem with the ESP but that seems to not be the case. Restarting only the ESP does not resolve the issue (I tried the ESPHome Restart functionality). So I assume the sensor itself stops working after some time. 

I was wondering which Firmware Version you are running (mine is 2.04.23101915, but I've had the same issue with 2.02.23090617, 1.2.23051810 did not work at all)

Any hint is appreciated, thanks!

**Comment by TillFleisch** [comment]
I have expeinced this issue as well on one of my sensors, the other one has been running stable, which indicates that this is a sensor issue. 
I have not looked up the Firmware versions, but I was able to find an updated version of the sensors Documentation, wherein a restart command is defined. Maybe this will hep resolve the issue.

**Comment by ElectricCookie** [comment]
I will try the other one I have. Thanks for letting me know

**Comment by TillFleisch** [comment]
Turns out, the version on my sensors was so old, that I was not able to retrieve the version number. Neither via Serial or the App provided by HiLink. After updating to V2.04.23101915 I was able to read the version number from the device. I have not yet figured out if the `getting stuck` issue persists with this version, it might also be a wiring problem on my side (The short pins and dupont connectors don't go well together).

I have started adding support for sensor configuration commands. The work-in-progress version in branch `sensor-configuration-support` has support for restarting and resetting the sensor. This may help resolve your issue.

**Comment by ElectricCookie** [comment]
It seems my other sensor is also having the same issue.

On a similar track as your troubleshooting: I have the sensor wired using the supplied cable.. the wires are quite long, I will try to shorten them and see if that resolves the issue.

**Comment by ElectricCookie** [comment]
Further narrowing down on the issue.  I will see if this esphome config will have the same sticky behaviour https://github.com/EverythingSmartHome/everything-presence-lite

**Comment by TillFleisch** [comment]
I've been using Firmware version `V2.04.23101915` for the last little bit and have not experienced sensors going dark. I believe it was a wiring issue on my side.
I did not check if Bluetooth worked the last time it failed (now I have Bluetooth disabled) but the sensor was noticeably colder than usual, again pointing at a power/wiring-related issue.

I think we can close this issue as non-software related. Let me know if the issue persists on your setup.
