### ISSUE TITLE
LD2450 Sensor stops detecting occupancy on "static" (non-moving) objects

### ISSUE THREAD

**Issue by barbiermathieu91** [TillFleisch/ESPHome-HLK-LD2450#14]
Hi, 
Thank you for the really good work.
I have noticed something while using my sensors across my home.
In rooms where moovement occurs frequently I have almost no issue.
However, in room where I might have really few moovement (for exemple while watching tv) the Esp Home stops returning my occupancy. I have checked with the HKtool app the sensor can see my position.

It looks like than when position is not changing, the sensor stop publishing information and esphome clears occupancy.

Thank you for the help or the explication

**Comment by TillFleisch** [comment]
While the LD2450 sensor can detect "static" targets, the detection can be a bit flaky at times. This depends on the sensor, its hardware (and firmware) and not on this custom component. Like most mm-Wave sensors, the LD2450 can detect "static" targets due to very small movements. While watching TV and sitting/laying *very*,  still the sensor can loose track. Thus reporting a false "unoccupied" state.

> I have checked with the HKtool app the sensor can see my position.

The moment you use your phone, the sensor picks up that motion and therefore tracks you.


To achieve more consistent tracking and to compensate for this downside of the LD2450 sensor `zones` can have a `target_timeout` property.

>The time after which a target within the zone is considered absent. This helps with continuous detection of non-moving targets. Targets which leave the zone via polygon boundaries are still detected as absent form the zone immediately. Defaults to `5s`.

(quote from readme)

Increasing this value will result in more consistent tracking, with the downside of potentially reporting "occupied" while a target has genuinely disappeared.
